Replace DrawerItems with DrawerNavigationItems
When upgrading from 3.x to 4.x, I updated the packages and imports per https://reactnavigation.org/docs/4.x/upgrading-from-3.x/ and everything worked except the drawer nav. When I used `DrawerItems`, I got an error:
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

My suggested change fixed my little Drawer Navigator. I think maybe this component was renamed in `react-navigation-drawer` 1.4.0, which is the version the migration guide recommends for 4.x.

This might be the wrong change. I saw the 2.4.0 [changelog](https://github.com/react-navigation/react-navigation/blob/4.x/packages/drawer/CHANGELOG.md#240-2020-02-24) mentions DrawerItems is re-exposed. In that case, perhaps the migration guide should be updated to recommend installing this newer version?

I lost motivation tracing the source with repos moving around, but hopefully this PR is somewhat helpful.